import FrictionSolidMechanicsCanonicalLaneLean.FrictionInterfaceModel

namespace HautevilleHouse
namespace FrictionSolidMechanicsCanonicalLaneLean

structure FrictionAdmittedObject where
  interfaceModel : FrictionInterfaceModel
  interfaceClosed : FrictionInterfaceClosed interfaceModel
  conclusion : Prop

end FrictionSolidMechanicsCanonicalLaneLean
end HautevilleHouse